




from pathlib import Path
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.config import REPORT_DIR


def generate_report(data: dict):

    report_path = REPORT_DIR / "analysis_report.pdf"

    doc = SimpleDocTemplate(str(report_path))

    styles = getSampleStyleSheet()

    elements = []

    # =============================
    # Title
    # =============================

    title = Paragraph(
        "<b><font size=18>AcousticSpace AI Analysis Report</font></b>",
        styles["Title"],
    )

    elements.append(title)
    elements.append(Spacer(1, 20))

    # =============================
    # Report Time
    # =============================

    generated_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    elements.append(
        Paragraph(
            f"<b>Generated:</b> {generated_time}",
            styles["Normal"],
        )
    )

    elements.append(Spacer(1, 20))

    # =============================
    # Prediction Table
    # =============================

    table_data = [

        ["File Name", data["filename"]],

        ["Prediction", data["prediction"]],

        ["Confidence", f'{data["confidence"]}%'],

        ["Risk Level", data["risk"]],

        ["Duration", f'{data["duration"]} sec'],

        ["Sample Rate", f'{data["sample_rate"]} Hz'],

        ["Analysis Time", f'{data["analysis_time"]} sec'],

    ]

    table = Table(table_data, colWidths=[170, 250])

    table.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),

            ]

        )

    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # =============================
    # Recommendation
    # =============================

    elements.append(

        Paragraph(

            "<b>AI Recommendation</b>",

            styles["Heading2"],

        )

    )

    elements.append(

        Paragraph(

            data["recommendation"],

            styles["BodyText"],

        )

    )

    elements.append(Spacer(1, 20))

    # =============================
    # Footer
    # =============================

    elements.append(

        Paragraph(

            "Generated by AcousticSpace v1.0",

            styles["Italic"],

        )

    )

    doc.build(elements)

    return report_path